Server:
  RunMode: debug
  HttpPort: :8080
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath:  C:\Users\chengxin.yin\Desktop\pro\gin-frame\storage\logs\
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:13306
  DBName: will
  TablePrefix: _blog
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
UploadFile:
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllExts:
    - .jpg
    - .jpeg
    - .png
Jaeger:
  Host: 127.0.0.1:6831
  Name: jaeger-server
# yaml 生成结构体工具: https://yaml2go.prasadg.dev/