Server:
  RunMode: debug
  HttpPort: :8080
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: C:\Users\Administrator\Desktop\go\code\frame\storage\logs\
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:13306
  DBName: go_frame
  TablePrefix: _blog
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30